### ISSUE TITLE
Maven Package Fails

### ISSUE THREAD

**Issue by jpizagno** [exasol/spark-connector#117] opened 2022-07-24 08:47 UTC
While running `mvn clean ; mvn package -DskipTests=true`  I get the error message at the end of this description.  

Here is more information:
- OS: Ubuntu 20
- `java -version` -> `openjdk version "1.8.0_312"`
- `scala -version` -> `Scala code runner version 3.1.3`
- `mvn -version `-> `Apache Maven 3.6.3`
- `git log` -> `commit ed0e0344df881091ca5659c42a0cdb92b3b8c70f ;  Date:   Wed May 11 14:12:34 2022 +0200`
- `git status` -> `On branch main ; Untracked Files : cs`

The error message:

```
mvn clean ; mvn package -DskipTests=true
....
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:06 min
[INFO] Finished at: 2022-07-24T10:39:49+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:3.3.0:shade (default) on project spark-connector: Error creating shaded jar: Some problems were encountered while processing the POMs:
[ERROR] [ERROR] 'build.plugins.plugin[io.github.evis:scalafix-maven-plugin_${scala.compat.version}].dependencies.dependency.artifactId' for com.github.liancheng:organize-imports_${scala.compat.version}:jar with value 'organize-imports_${scala.compat.version}' does not match a valid id pattern. @ line 533, column 25
[ERROR] [ERROR] 'build.plugins.plugin[io.github.evis:scalafix-maven-plugin_${scala.compat.version}].dependencies.dependency.artifactId' for com.github.vovapolu:scaluzzi_${scala.compat.version}:jar with value 'scaluzzi_${scala.compat.version}' does not match a valid id pattern. @ line 538, column 25
[ERROR] : 2 problems were encountered while building the effective model for com.exasol:spark-connector:1.2.0
[ERROR] [ERROR] 'build.plugins.plugin[io.github.evis:scalafix-maven-plugin_${scala.compat.version}].dependencies.dependency.artifactId' for com.github.liancheng:organize-imports_${scala.compat.version}:jar with value 'organize-imports_${scala.compat.version}' does not match a valid id pattern. @ line 533, column 25
[ERROR] [ERROR] 'build.plugins.plugin[io.github.evis:scalafix-maven-plugin_${scala.compat.version}].dependencies.dependency.artifactId' for com.github.vovapolu:scaluzzi_${scala.compat.version}:jar with value 'scaluzzi_${scala.compat.version}' does not match a valid id pattern. @ line 538, column 25
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by jpizagno** [comment] 2022-07-24 09:04
@morazow  Is this just an incompatible version of scala ?

**Comment by morazow** [comment] 2022-07-25 07:10
Hello @jpizagno,

Thanks for the feedback! 

I am going to check it soon. Yes, you might be right that is related to Scala versions of compiler plugins.

**Comment by morazow** [comment] 2022-08-02 08:43
Hey @jpizagno,
I think the issue is with shade plugin. Somehow, it cannot pickup property values for inner plugin dependencies by default.

```
            <plugin>
                <groupId>io.github.evis</groupId>
                <artifactId>scalafix-maven-plugin_${scala.compat.version}</artifactId>
                <version>0.1.4_0.9.31</version>
                <dependencies>
                    <dependency>
                        <groupId>com.github.liancheng</groupId>
                        <artifactId>organize-imports_${scala.compat.version}</artifactId>
                        <version>0.6.0</version>
                        <scope>compile</scope>
                    </dependency>
                    <dependency>
                        <groupId>com.github.vovapolu</groupId>
                        <artifactId>scaluzzi_${scala.compat.version}</artifactId>
                        <version>0.1.21</version>
                        <scope>compile</scope>
                    </dependency>
                </dependencies>
            </plugin>
```
So far, I could not understand why they are not picked up by default activation profile.

However, explicitly setting the profile value works fine:

```
mvn clean; mvn package -DskipTests=true -Pspark3.2
```

**Note:** At this moment you may get the audit error, you can skip them using `ossindex.skip`:
```
mvn clean; mvn package -DskipTests=true -Dossindex.skip=true -Pspark3.2
```
or wait until the #119 is merged.

**Comment by morazow** [comment] 2022-08-04 10:13
Hey @jpizagno,
Can we close this issue?

Thanks and best

**Comment by morazow** [comment] 2022-08-05 11:05
Hi @jpizagno,
We are going to close this ticket for now. Please let us know if there are more issues.

**Closed by morazow** 2022-08-05 11:05 UTC
Labels: bug

**Comment by jpizagno** [comment] 2022-08-07 18:36
> Hi @jpizagno, We are going to close this ticket for now. Please let us know if there are more issues.

Hey @morazow Sorry for the late reply. (I was on vacation.)    

Confirmed.  If I use the latest master and java 11, then `mvn clean; mvn package -DskipTests=true -Pspark3.2` successfully builds a Jar file in target.

thanks
